Fs may19 olha
mate-academy/layout_enclosures pull request #112
Opened 2019-05-27 17:26 UTC by OlgaLyubicheva

- [DEMO LINK](https://olgalyubicheva.github.io/layout_enclosures/) <br>
- [TEST REPORT LINK](https://olgalyubicheva.github.io/layout_enclosures/report/html_report/)

2019-05-28 14:07 UTC, vpolets requested changes

2019-05-28 14:07 UTC, vpolets commented on src/style.css
> +  border: 1px solid #e75551;
Дублювання коду. Старайся не повторювати код. Винось все в збірні класи. Створи додатковий клас типу box і йому присвоюй всі властивості які повторються із блока в блок.

2019-05-28 14:07 UTC, vpolets commented on src/style.css
> +div {
Краще не стилізувати теги. Стилізуй класи.

2019-05-28 19:23 UTC, OlgaLyubicheva commented on src/style.css
> +div {
body теж не можна?

2019-05-28 19:34 UTC, OlgaLyubicheva commented on src/style.css
> +  border: 1px solid #e75551;
А можна 
.div-yellow, .content {width: 100%;}
а потім те, що не повторюється окремо в
.div-yellow {...}
.content {...} ?

2019-05-29 21:14 UTC, vpolets commented on src/style.css
> +div {
body можна, але не захоплюйся:)

2019-05-29 21:15 UTC, vpolets commented on src/style.css
> +  border: 1px solid #e75551;
а тут треба width: 100%? Думаю ні. Блоки і так намагаються зайняти весь доступний простір.

2019-05-29 21:16 UTC, vpolets commented on src/style.css
> +  border: 1px solid #e75551;
Винеси бордер в окремий клас.

2019-05-29 21:16 UTC, vpolets requested changes
Дороби

2019-05-30 13:29 UTC, mgrinko commented on src/style.css
> +  /*width: 100%;*/
комментарии стоит удалять

2019-05-30 13:29 UTC, mgrinko approved these changes

2025-06-05 13:31 UTC, closed without merging