Fs jul19 yevhen sag - enclosures solution
mate-academy/layout_enclosures pull request #150
Opened 2019-07-23 19:40 UTC by yevhen-sahach

2019-07-24 13:30 UTC, YuriiHoliuk requested changes

2019-07-24 13:30 UTC, YuriiHoliuk commented on src/style.css
> +  padding: 10px;
do not repeat

2019-07-24 13:30 UTC, YuriiHoliuk commented on src/style.css
> +div {
will be better to add common class instead of add styles to div

2019-07-24 15:36 UTC, yevhen-sahach commented
I've styled class instead of tag and removed repeating, check it out please

2019-07-25 15:27 UTC, irenhh approved these changes

2023-01-14 15:39 UTC, closed without merging