natalia-lypovyk: enclosures
mate-academy/layout_enclosures pull request #256
Opened 2019-12-16 17:47 UTC by natalia-lypovyk

https://natalia-lypovyk.github.io/layout_enclosures/
https://natalia-lypovyk.github.io/layout_enclosures/report/html_report/

2019-12-16 19:21 UTC, danheim requested changes

2019-12-16 19:21 UTC, danheim commented on src/style.css
> +  margin: 20px 20px 40px;
задай для body padding: 20px а тут оставь `margin-bottom: 40px;`
лучше дать родительскому контейнеру padding, чем дочернему margin

2019-12-16 19:21 UTC, danheim commented on src/style.css
> +  padding: 10px;
padding: 10px - используется три раза, подумай как задать свойство лишь один раз

2019-12-17 08:33 UTC, irenhh approved these changes

2022-12-06 08:41 UTC, closed without merging