Develop
mate-academy/layout_enclosures pull request #279
Opened 2019-12-17 20:12 UTC by LeonidShv

https://leonidshv.github.io/layout_enclosures/
https://leonidshv.github.io/layout_enclosures/report/html_report/

2019-12-18 07:26 UTC, irenhh requested changes

2019-12-18 07:26 UTC, irenhh commented on src/index.html
> +        <p class="button">
к чему тут button?

2019-12-18 07:26 UTC, irenhh commented on src/index.html
> +  <div class="div-widt-margin">
что это за название класса такое?

2019-12-18 07:26 UTC, irenhh commented on src/style.css
> +  margin-left: 20px;
добавь падинги для body

2019-12-18 07:26 UTC, irenhh commented on src/style.css
> +.m-top {
мы с тобой говорили о классе с таким именем

2019-12-18 07:26 UTC, irenhh commented on src/style.css
> +.button {
создай общий класс и стилизуй по нему

2019-12-18 08:01 UTC, LeonidShv commented on src/index.html
> +        <p class="button">
external - отвечает за синий фонй(внешний див)
mid - за желтый фон( центральный)
button - за серый фон,(самый нижний)

2019-12-18 09:00 UTC, LeonidShv commented on src/index.html
> +        <p class="button">
вместо button поставлю internal

2019-12-18 09:00 UTC, LeonidShv commented on src/index.html
> +  <div class="div-widt-margin">
я посчитал что так норм))
сейчас попробую переименовать

2019-12-18 10:50 UTC, gestap commented on src/index.html
> +  <div>
навіщо тобі ця обгортка? видали її

2019-12-18 10:50 UTC, gestap commented on src/index.html
> +  <div>
і тут

2019-12-18 10:50 UTC, gestap commented on src/index.html
> +  <div id="qa-block">
тут теж

2019-12-18 10:50 UTC, gestap commented on src/style.css
> +  box-sizing: border-box;
добав цю властивість тільки класу в якому задаєш width

2019-12-18 10:50 UTC, gestap commented on src/style.css
> +  width: 350px;
не стилізуй через теги, для цього використовуй клас

2019-12-18 10:50 UTC, gestap commented on src/style.css
> +}
і тут теж

2019-12-18 11:00 UTC, LeonidShv commented on src/index.html
> +  <div>
к этому диву привязаны стили
до этого там стояло плохое название класса

2019-12-18 11:00 UTC, LeonidShv commented on src/index.html
> +  <div>
мне сказали, что плохое.

2019-12-18 18:40 UTC, LeonidShv commented on src/style.css
> +}
До этого тут стоял класс .top, который для самого верхнего указывал margin-top: 20px;
а для остальных блоков у меня где то стояло margin-top: 40px;
но мне сказали его убрать и я сделал такой велосипед

мне вернуть как было?

2019-12-18 18:41 UTC, LeonidShv commented on src/style.css
> +  width: 350px;
исправил, задал всем блокам класс .block-width

2019-12-18 18:45 UTC, LeonidShv commented on src/index.html
> +  <div>
теперь более явно привязал стили к этому диву

2019-12-18 18:45 UTC, LeonidShv commented on src/index.html
> +  <div>
теперь более явно привязал стили к этому диву

2019-12-18 18:46 UTC, LeonidShv commented on src/index.html
> +  <div id="qa-block">
теперь более явно привязал стили к этому диву

2019-12-18 18:46 UTC, LeonidShv commented on src/style.css
> +  box-sizing: border-box;
Исправил

2019-12-19 07:37 UTC, irenhh requested changes

2019-12-19 07:37 UTC, irenhh commented on src/style.css
> +}
добавь просто клас этому диву

2019-12-19 07:37 UTC, irenhh commented on src/index.html
> +  <div id="qa-block" class="block-width">
самый внешний див не нужен, зачем их столько?

2019-12-19 10:10 UTC, LeonidShv commented on src/index.html
> +  <div id="qa-block" class="block-width">
Увидел что можно обьеденить)

2019-12-19 10:13 UTC, LeonidShv commented on src/style.css
> +}
все понял

2019-12-19 10:25 UTC, irenhh requested changes

2019-12-19 10:25 UTC, irenhh commented on src/index.html
> +    <div class="external common-border-padding block-width">
в стилях тоже объедини

2019-12-19 11:29 UTC, LeonidShv commented on src/index.html
> +    <div class="external common-border-padding block-width">
сделал

2019-12-19 11:36 UTC, irenhh approved these changes

2023-02-16 16:43 UTC, closed without merging