solution
mate-academy/layout_enclosures pull request #285
Opened 2020-02-24 09:40 UTC by crash2bash

- [DEMO LINK](https://crash2bash.github.io/layout_enclosures/) <br>
- [TEST REPORT LINK](https://crash2bash.github.io/layout_enclosures/report/html_report/)

2020-02-24 15:42 UTC, 8hokage requested changes

2020-02-24 15:42 UTC, earthhuman41 commented on src/style.css
> +  border: 1px solid #e75551;
i think repeated property you can take it to separate class

2020-02-24 16:10 UTC, crash2bash commented on src/style.css
> +  border: 1px solid #e75551;
Согласен, спасибо за дельные замечания 👍

2020-02-25 09:39 UTC, 8hokage approved these changes

2023-03-22 09:27 UTC, closed without merging