'solution4'
mate-academy/layout_enclosures pull request #322
Opened 2020-02-24 18:18 UTC by FaychakA

2020-02-24 18:37 UTC, FaychakA commented
- [DEMO LINK](https://FaychakA.github.io/layout_enclosures/) <br>
 - [TEST REPORT LINK](https://FaychakA.github.io/layout_enclosures/report/html_report/)

2020-02-25 09:27 UTC, 8hokage requested changes

2020-02-25 09:27 UTC, earthhuman41 commented on src/style.css
> +.box_content {
create common class for these

2020-02-25 12:08 UTC, vkryvytskyi approved these changes

2026-01-12 09:49 UTC, closed without merging