Solution
mate-academy/layout_enclosures pull request #367
Opened 2020-04-21 19:39 UTC by ogsevko

- [DEMO LINK](https://ogsevko.github.io/layout_enclosures/)
- [TEST REPORT LINK](https://ogsevko.github.io/layout_enclosures/report/html_report/)

2020-04-22 08:34 UTC, irenhh requested changes
fix indentations

2020-04-22 08:34 UTC, irenhh commented on src/style.css
> +  margin-bottom: 40px;
don't write margin twice if you already mentioned a short note

2020-04-22 16:03 UTC, irenhh requested changes

2020-04-22 16:03 UTC, irenhh commented on src/index.html
> +    </div>
```suggestion
      <div class="box grayish">
        У програмуванні замиканням називають підпрограму, що виконується в
        середовищі, яке містить одну або більше зв’язаних змінних. Підпрограма має доступ до цих змінних під час виконання.
      </div>
    </div>
```

2020-04-22 16:08 UTC, ogsevko commented on src/index.html
> +    </div>
What exactly do I have to fix here?

2020-04-23 06:41 UTC, irenhh requested changes
usually, you will receive one comment and fix the same mistake everywhere.
You fixed only in the place I added my comment, what about other similar places?

2020-04-23 06:59 UTC, ogsevko commented
Sorry. At first I didn't get exactly what fI had to fix and just commited your change via a button right in this thread. Then I realized what was wrong with my code, so I changed all three occasions and committed, pushed (the develop branch) and published it. But it seems that it didn't work.

2020-04-23 09:11 UTC, ogsevko commented
Apologies for this mess. I'm still new to git and sometimes it gets confusing. Hope all is good now. Thank you!

2020-04-23 15:12 UTC, irenhh approved these changes

2023-12-26 21:51 UTC, closed without merging