Solution
mate-academy/layout_enclosures pull request #391
Opened 2020-06-28 17:36 UTC by tykhan

- [DEMO LINK](https://tykhan.github.io/layout_enclosures/) <br>
- [TEST REPORT LINK](https://tykhan.github.io/layout_enclosures/report/html_report/)

2020-06-30 15:13 UTC, denys-cheporniuk requested changes

2020-06-30 15:13 UTC, Denchepornyuk commented on src/index.html
> +        <div class="grey">In programming languages, a closure is a technique for implementing lexically scoped name binding in a language with first-class functions. Operationally, a closure is a rec
перенось текст на нову лінію після тегів)

2020-06-30 15:13 UTC, Denchepornyuk commented on src/style.css
> +* {
checklist

2020-06-30 15:13 UTC, Denchepornyuk commented on src/style.css
> +div {
не стилізуй теги

2020-06-30 15:45 UTC, tykhan commented on src/style.css
> +div {
Чому в деяких випадках не можна стилізувати теги? Лишні класи теоретично можуть тільки заплутати

2020-06-30 16:32 UTC, Denchepornyuk commented on src/style.css
> +  padding: 0;
в body є дефолтний padding ?)

2020-06-30 16:32 UTC, Denchepornyuk commented on src/style.css
> +div {
ми не стилізуємо теги, тому що грамотно розтавлені класи ніколи не запутают в коді, це як підказка для девелопера, що робить цей блок. Якщо стилізувати теги то ці стилі застосуються для всіх тегі цього типу на сторінці. І коли виникає ситуація добавити тег для якого ці стилі не потрібні то прийдеться перебивати їх іншими стилями, а це вже костиль. Тому в практиці девелопери стилізують тільки класи)
`body` - це виняток, зазвичай такий тег тільки один на сторінкі і для нього можна записати зальні стилі, типу шрифт для сторінки

2020-07-01 08:06 UTC, denys-cheporniuk approved these changes

2023-01-29 14:57 UTC, closed without merging