Task 4 'Enclosures' - Done!
mate-academy/layout_enclosures pull request #452
Opened 2020-08-25 14:40 UTC by Atteroot

- [DEMO LINK](https://Atteroot.github.io/layout_enclosures/)
- [TEST REPORT LINK](https://Atteroot.github.io/layout_enclosures/report/html_report/)

2020-08-25 17:24 UTC, solaryasha requested changes

2020-08-25 17:24 UTC, solaryasha commented on src/style.css
> +div {
Давай зробимо спеціальний клас для цих правил

2020-08-25 17:24 UTC, solaryasha commented on src/style.css
> +.text p {
І тут також

2020-08-25 17:24 UTC, solaryasha commented on src/style.css
> +div .text {
І тут

2020-08-26 07:58 UTC, Atteroot commented on src/style.css
> +div {
Fixed!

2020-08-26 07:58 UTC, Atteroot commented on src/style.css
> +.text p {
Fixed!

2020-08-26 07:58 UTC, Atteroot commented on src/style.css
> +div .text {
Fixed!

2020-08-26 09:49 UTC, solaryasha approved these changes
🚀

2021-03-23 19:00 UTC, closed without merging