enclosures solution
mate-academy/layout_enclosures pull request #553
Opened 2021-01-11 19:17 UTC by yashnyi

- [DEMO LINK](https://yashnyi.github.io/layout_enclosures/) <br>
- [TEST REPORT LINK](https://yashnyi.github.io/layout_enclosures/report/html_report/)

2021-01-11 21:11 UTC, solaryasha requested changes

2021-01-11 21:11 UTC, solaryasha commented on src/style.css
> +  padding: 10px;
Це правило повторюється три рази, задай його для класу `block`

2021-01-12 07:29 UTC, yashnyi commented on src/style.css
> +  padding: 10px;
дякую, виправив

2021-01-12 08:22 UTC, solaryasha approved these changes
Well done 🚀

2025-09-01 20:49 UTC, closed without merging