Solution
mate-academy/layout_enclosures pull request #615
Opened 2021-03-18 11:32 UTC by igor-stasiv

https://igor-stasiv.github.io/layout_enclosures/
https://igor-stasiv.github.io/layout_enclosures/report/html_report/

2021-03-19 18:14 UTC, vsm2k17 requested changes

2021-03-19 18:14 UTC, vsm2k17 commented on src/index.html
> +            In programming languages, a closure is a technique for implementing lexically scoped name binding in a language with first-class functions. Operationally, a closure is a record storing a
80 symbols max per line

2021-03-19 18:14 UTC, vsm2k17 commented on src/style.css
> +  box-sizing: border-box;
use * selector 
```
* {
box-sizing: border-box;
}

2021-03-22 11:43 UTC, aliceblunt8 approved these changes

2024-12-15 15:34 UTC, closed without merging