Fs may19 dmitry y
mate-academy/layout_enclosures pull request #88
Opened 2019-05-25 09:53 UTC by danheim

- [DEMO LINK](https://danheim.github.io/layout_enclosures/) <br>
- [TEST REPORT LINK](https://danheim.github.io/layout_enclosures/report/html_report/)

2019-05-28 14:50 UTC, vpolets requested changes
Позбудься дублювання коду. Створи додаткові класи.

2019-05-28 14:50 UTC, vpolets commented on src/style.css
> +  box-sizing: border-box;
Не роби так. Винеси в окремий клас.

2019-05-28 14:50 UTC, vpolets commented on src/style.css
> +  border: 1px solid #e75551;
Дублювання коду. Створи збірний клас.

2019-05-29 02:31 UTC, mgrinko commented on src/style.css
> +  margin: 10px;
это лучше делать `padding: ` у родителя

2019-05-29 02:32 UTC, mgrinko commented on src/style.css
> +  margin: 20px 20px 40px;
20 лучше сделать `padding` у `body`

2019-05-29 02:33 UTC, mgrinko commented on src/index.html
>  <script type="text/javascript" src="./main.js"></script>
это лучше удалить если не пользуешься

2019-05-29 02:33 UTC, mgrinko requested changes
Жду правок

2019-05-29 02:52 UTC, mgrinko commented on src/style.css
> +  padding: 10px;
это можно было вынести в общий стиль для `div`

2019-05-29 02:52 UTC, mgrinko approved these changes

2019-05-29 02:52 UTC, danheim commented on src/style.css
> +  padding: 10px;
Заметил после того, как покрасил в желтый цвет. Уже отправил ;)

2026-08-23 16:51 UTC, closed without merging